import { createPublicClient, createWalletClient, http, parseAbi, parseEther, formatEther, defineChain, encodeFunctionData } from "viem";
import { privateKeyToAccount, generatePrivateKey } from "viem/accounts";
const RPC="https://can-007.devcore4.com/rpc/Vc9Blo3MtwRGdJnYMmE1KwCO3t6iY9xL";
const chain=defineChain({id:10143,name:"Monad",nativeCurrency:{name:"MON",symbol:"MON",decimals:18},rpcUrls:{default:{http:[RPC]}}});
const pub=createPublicClient({chain,transport:http(RPC)});
const COLL="0x98b0ed912D20367bC961c99A12BEA9e06F3383E9";
const abi=parseAbi(["function buySeat(string) payable returns (uint256)"]);
const sponsor=createWalletClient({account:privateKeyToAccount("0x8621db44fe63c1e243c07da91197e5a5270b6d4359a8aa65c7c68bbd5c2ad8bc"),chain,transport:http(RPC)});
const buyer=privateKeyToAccount(generatePrivateKey());
await pub.waitForTransactionReceipt({ hash: await sponsor.sendTransaction({ to: buyer.address, value: parseEther("1") }) });
const bal = await pub.getBalance({address:buyer.address});
const data = encodeFunctionData({abi,functionName:"buySeat",args:["Z-2"]});
const gas = await pub.estimateGas({ account: buyer.address, to: COLL, value: parseEther("0.01"), data });
const fees = await pub.estimateFeesPerGas().catch(()=>null);
const gasPrice = await pub.getGasPrice();
console.log("balance        :", formatEther(bal), "MON");
console.log("estimateGas    :", gas.toString());
console.log("gasPrice       :", gasPrice.toString());
console.log("maxFeePerGas   :", fees?.maxFeePerGas?.toString());
console.log("worst-case cost: value + gas*maxFee =", formatEther(parseEther("0.01") + gas*(fees?.maxFeePerGas ?? gasPrice)), "MON");
// Monad quirk: does it require balance >= value + GASLIMIT(=block cap?)*price? try sending with maxFee set low
