import { createPublicClient, createWalletClient, http, parseAbi, parseEther, formatEther, defineChain, keccak256, toBytes, encodeAbiParameters } from "viem";
import { privateKeyToAccount, generatePrivateKey } from "viem/accounts";
const RPC="https://can-007.devcore4.com/rpc/Vc9Blo3MtwRGdJnYMmE1KwCO3t6iY9xL";
const chain=defineChain({id:10143,name:"Monad",nativeCurrency:{name:"MON",symbol:"MON",decimals:18},rpcUrls:{default:{http:[RPC]}}});
const pub=createPublicClient({chain,transport:http(RPC)});
const FACTORY="0x57688e8945508c9ac860ab6DAe8B1761C1E61087";
const SPONSOR="0x8621db44fe63c1e243c07da91197e5a5270b6d4359a8aa65c7c68bbd5c2ad8bc";
const GATE="0xe1cf09908e2a03578b2b73bb225c720ba43fe00312c9d005b8cf337eb5b58dbd";
const abi=parseAbi(["function events(uint256) view returns (address)","function buySeat(string) payable returns (uint256)","function seatListing(bytes32) view returns (uint16,uint256,bool,uint256)","function checkInNonce(address) view returns (uint256)","function setGateCode(bytes32)","function checkIn(uint256,string,bytes)","function ticket(uint256) view returns ((uint16,uint256,uint64,uint64,uint256))","function listSeats(string[],uint16,uint256)","function ownerOf(uint256) view returns (address)"]);
const coll=await pub.readContract({address:FACTORY,abi,functionName:"events",args:[0n]});
const sponsor=createWalletClient({account:privateKeyToAccount(SPONSOR),chain,transport:http(RPC)});
const gate=createWalletClient({account:privateKeyToAccount("0x5213b386f221f3031a06c173ceb4c18b9e55e6152241a49e0f782113f92a4ed6"),chain,transport:http(RPC)}); // organizer can list
const gateDev=createWalletClient({account:privateKeyToAccount(GATE),chain,transport:http(RPC)});
const SEAT="E2E-"+Date.now().toString().slice(-5);
await pub.waitForTransactionReceipt({hash: await gate.writeContract({address:coll,abi,functionName:"listSeats",args:[[SEAT],0,parseEther("0.01")],gas:400000n})});
const buyer=privateKeyToAccount(generatePrivateKey());
await pub.waitForTransactionReceipt({hash: await sponsor.sendTransaction({to:buyer.address,value:parseEther("0.5")})});
console.log("buyer funded:", formatEther(await pub.getBalance({address:buyer.address})), "MON");
const wc=createWalletClient({account:buyer,chain,transport:http(RPC)});
await pub.waitForTransactionReceipt({hash: await wc.writeContract({address:coll,abi,functionName:"buySeat",args:[SEAT],value:parseEther("0.01"),gas:600000n})});
const [,,,tid]=await pub.readContract({address:coll,abi,functionName:"seatListing",args:[keccak256(toBytes(SEAT))]});
console.log(`bought ${SEAT} → token #${tid}`);
const CODE="DRUM-9090";
await pub.waitForTransactionReceipt({hash: await gateDev.writeContract({address:coll,abi,functionName:"setGateCode",args:[keccak256(toBytes(CODE))],gas:120000n})});
const nonce=await pub.readContract({address:coll,abi,functionName:"checkInNonce",args:[buyer.address]});
const digest=keccak256(encodeAbiParameters([{type:"address"},{type:"uint256"},{type:"uint256"},{type:"uint256"},{type:"bytes32"}],[coll,10143n,tid,nonce,keccak256(toBytes(CODE))]));
const sig=await buyer.signMessage({message:{raw:digest}});
const r=await pub.waitForTransactionReceipt({hash: await gateDev.writeContract({address:coll,abi,functionName:"checkIn",args:[tid,CODE,sig],gas:500000n})});
const usedAt=(await pub.readContract({address:coll,abi,functionName:"ticket",args:[tid]}))[3];
const owner=await pub.readContract({address:coll,abi,functionName:"ownerOf",args:[tid]});
console.log(`check-in tx: ${r.status}`);
console.log(`ticket usedAt: ${usedAt} (nonzero = checked in)`);
console.log(`ticket now owned by event wallet: ${owner.toLowerCase()==="0x4FcFba4127025B2565C0eB7BE6bcEF381D36F4bC".toLowerCase()}`);
console.log(r.status==="success" && usedAt>0n ? "\n✅ FULL FLOW WORKS: buy → code → sign → gate check-in" : "\n❌ still broken");
